### ISSUE TITLE
Use persistence to store time zone between runs

### ISSUE THREAD

**Issue by pneumaticdeath** [davidfg4/pebble-day-night#1]
Possible improvement: use persistent state to store time zones between runs so that the watchface doesn't assume GMT until it can get confirmation from the phone.

**Comment by pneumaticdeath** [comment]
Looks like you're already doing that, though it doesn't seem to work on the version I got from the appstore

**Comment by rengianforte** [comment]
Yeah I tried implementing this, but it didn't work. I even tried the sample code for persistence and that didn't work for me either.

The appstore version is the exact same thing as the current version here.

**Comment by pneumaticdeath** [comment]
I think I got it working.  I can push the changes to github if you like.
 I'm not 100% sure what did it, but I think moving the load section up to
before declaring the window init handlers did it.  The rest was basically
just logging, and moving the persist write to the message handler from the
deinit().

Here's the diff:
mitch@phobos:~/pebble-dev/workspace/pebble-day-night$ git diff
diff --git a/appinfo.json b/appinfo.json
index 65ab7d8..7ebb0f9 100644
--- a/appinfo.json
+++ b/appinfo.json
@@ -3,8 +3,8 @@
   "shortName": "Day Night",
   "longName": "Day and Night Earth Watchface",
   "companyName": "David Gianforte",
-  "versionCode": 1,
-  "versionLabel": "1.2",
-  "versionCode": 2,
-  "versionLabel": "1.3",
  "watchapp": {
   "watchface": true
  },
  diff --git a/src/shadow.c b/src/shadow.c
  index 7cb4b8c..e6e8dc7 100644
  --- a/src/shadow.c
  +++ b/src/shadow.c
  @@ -99,6 +99,12 @@ static void
  app_message_inbox_received(DictionaryIterator *iterator, void *conte
  int unixtime = t->value->int32;
  int now = (int)time(NULL);
  time_offset = unixtime - now;
-  status_t s = persist_write_int(TIME_OFFSET_PERSIST, time_offset);
-  if (s) {
-    APP_LOG(APP_LOG_LEVEL_DEBUG, "Saved time offset %d with status %d",
  time_offset, (int) s);
-  } else {
-    APP_LOG(APP_LOG_LEVEL_DEBUG, "Failed to save time offset with status
  %d", (int) s);
-  }
  draw_earth();
  }

@@ -155,6 +161,13 @@ static void window_unload(Window *window) {
 static void init(void) {
   redraw_counter = 0;
-  // Load the UTC offset, if it exists
-  time_offset = 0;
-  if (persist_exists(TIME_OFFSET_PERSIST)) {
-    time_offset = persist_read_int(TIME_OFFSET_PERSIST);
-    APP_LOG(APP_LOG_LEVEL_DEBUG, "loaded offset %d", time_offset);
-  }
  +
  world_bitmap = gbitmap_create_with_resource(RESOURCE_ID_WORLD);
  
  window = window_create();
  @@ -166,13 +179,6 @@ static void init(void) {
  const bool animated = true;
  window_stack_push(window, animated);
-  // Load the UTC offset, if it exists
-  time_offset = 0;
-  if (persist_exists(TIME_OFFSET_PERSIST)) {
-    APP_LOG(APP_LOG_LEVEL_DEBUG, "loaded offset");
-    time_offset = persist_read_int(TIME_OFFSET_PERSIST);

## \-  }

   s = malloc(STR_SIZE);
   tick_timer_service_subscribe(MINUTE_UNIT, handle_minute_tick);

@@ -182,7 +188,8 @@ static void init(void) {

 static void deinit(void) {
   // this write doesn't actully work for some reason
-  persist_write_int(TIME_OFFSET_PERSIST, time_offset);
-  // Checking to see if it works better at a different location.
-  // persist_write_int(TIME_OFFSET_PERSIST, time_offset);
  tick_timer_service_unsubscribe();
  free(s);
  window_destroy(window);

**Comment by rengianforte** [comment]
Oh nice. Feel free to make a pull request, otherwise I will just apply the diff and commit it myself.

**Comment by pneumaticdeath** [comment]
I'm newish to git, so it took me a minute to figure out how to do that.  Thanks for giving me an excuse to figure this stuff out.  I like your watchface.

**Comment by rengianforte** [comment]
Cool. I tested it and it worked! (I had to update my watch from 2.0-BETA4 to 2.0.1 for it to work. It must not have been implemented in the beta.)

I merged your pull request into my branch and published the newest app to the store.
